@startuml "Марсианская агроферма. Базовый функциональный сценарий"

title "Марсианская агроферма. Базовый функциональный сценарий\nПримечание: рассматривается только позитивный сценарий (ошибок нет)"

autonumber

participant "1. Связь" as conn
participant "2. Система\nуправления" as control 
participant "3. Выращивание\nкартофеля" as cultivation
participant "4. Компостирование\nи почвоподготовка" as  composting
participant "5. Контроль\nи селекция" as qa 
participant "6. Хранилище\nурожая и\nрасконсервация" as storage

control -> cultivation++: запуск процесса выращивания 

loop Начало и процесс выращивания 
    cultivation -> cultivation: самопроверка\nанализ условий
    cultivation --> control--: запрос кондиционирования,\nводоснабжения, энергии
    control -> conn: запросы ресурсов\nу внешних систем
    conn -> conn: взаимодействие\nс внешними системами
    conn --> control: ресурсы выданы
    control -> cultivation: ресурсы выданы
    cultivation -> cultivation: контроль параметров\nстарт (продолжение)\nвыращивания

    group Контроль жизненных показателей
       cultivation -> cultivation: анализ корнеплодов и ботвы
       cultivation -> composting: извлечь растения\nиз заданных ячеек\nдля компостирования
       composting -> composting: выполнение запроса
       cultivation -> qa: извлечь корнеплоды\nиз заданных ячеек\nв хранилище
       qa -> qa: анализ качества клубней
       qa -> composting: утилизировать некачественные клубни
       qa -> storage: поместить в хранилище нормальные клубни
       qa -> storage: поместить в фонд селекции наиболее крупные клубни
       cultivation -> qa: установить клубни для выращивания в заданные ячейки
       qa -> storage: выдать клубни для рассады
       storage --> qa: клубни
       qa -> qa: контроль клубней\nзамена негодных клубней
       qa --> cultivation: клубни для рассады
    end
end 


@enduml