@startuml "Марсианская агроферма. Базовый функциональный сценарий"

title "Марсианская агроферма\nБазовый функциональный сценарий выращивания картофеля\nПримечание: рассматривается только позитивный сценарий (ошибок нет)"

autonumber

participant "1. Связь" as conn
participant "2. Система\nуправления" as control 
participant "3. Выращивание\nкартофеля" as cultivation
participant "4. Компостирование\nи почвоподготовка" as  composting
participant "5. Контроль\nи селекция" as qa 
participant "6. Хранилище\nурожая и\nрасконсервация" as storage

group Активация и подготовка работы фермы
control -> composting++: активация
composting -> composting: самодиагностика и\nпервичное ферментирование компоста
composting --> control--: статус
control -> qa++: активация
qa -> qa: самодиагностика и\nкалибровка
qa --> control--: статус
control -> storage++: активация
storage -> storage: самодиагностика и\nпереучёт
storage --> control--: статус
control -> cultivation++: запуск процесса выращивания 
end

loop Начало и процесс выращивания 
    cultivation -> cultivation: самопроверка\nанализ условий
    cultivation --> control--: запрос кондиционирования,\nводоснабжения, энергии
    control -> conn: запросы ресурсов\nу внешних систем
    conn -> conn: взаимодействие\nс внешними системами
    conn --> control: ресурсы выданы
    control -> cultivation++: ресурсы выданы
    cultivation -> cultivation: контроль параметров\nстарт (продолжение)\nвыращивания

    group Контроль жизненных показателей
       cultivation -> cultivation: анализ корнеплодов и ботвы
       cultivation -> composting: извлечь растения\nиз заданных ячеек\nдля компостирования
       composting -> composting: выполнение запроса
       cultivation -> qa++: извлечь корнеплоды\nиз заданных ячеек\nв хранилище
       qa -> qa: анализ качества клубней
       qa -> composting--: утилизировать некачественные клубни
       activate composting
       composting -> composting: утилизация        
       deactivate composting
       qa -> storage++: поместить в хранилище нормальные клубни
       storage -> storage--: размещение\nнормальных клубней
       qa -> storage++: поместить в фонд селекции наиболее крупные клубни
       storage -> storage--: размещение\nв селекционном\nфонде
       cultivation -> qa: установить клубни для выращивания в заданные ячейки
       qa -> storage++: выдать клубни для рассады
       storage -> storage: извлечение\nселекционных клубней
       storage --> qa--: клубни
       activate qa
       qa -> qa: контроль клубней\nзамена негодных клубней
       qa --> cultivation--: клубни для рассады
    end
    deactivate cultivation
end 


@enduml

@startuml "Марсианская агроферма. Обновление конфигурации с Земли"

title Марсианская агроферма\nОбновление конфигурации с Земли\nТолько позитивный сценарий


participant "СМС" as sms
participant "1. Связь" as conn
participant "2. Система\nуправления" as control 
participant "3. Выращивание\nкартофеля" as cultivation
participant "4. Компостирование\nи почвоподготовка" as  composting
participant "5. Контроль\nи селекция" as qa 
participant "6. Хранилище\nурожая и\nрасконсервация" as storage

note over sms 
система межпланетной
связи - получает информацию 
с Земли, передаёт на Землю 
статусы и телеметрию
end note

sms -> conn++: новые параметры\nтехнологических процессов
conn -> control++: новые параметры\nтехнологических процессов

control -> cultivation++: новые параметры\nвыращивания
cultivation -> cultivation: обновление параметров
cultivation --> control--: параметры обновлены

control -> composting++: новые параметры\nкомпостирования
composting -> composting: обновление параметров
composting --> control--: параметры обновлены

control -> qa++: новые параметры\nконтроля качества
qa -> qa: обновление параметров
qa --> control--: параметры обновлены

control -> storage++: новые параметры\nхранения
storage -> storage: обновление параметров
storage --> control--: параметры обновлены

control --> conn--: параметры обновлены
conn --> sms--: параметры обновлены

@enduml